#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <stdio.h>
#include <iostream>
#include <GLFW/glfw3native.h>
#include <stdint.h>
#include <math.h>
#include <glm/vec3.hpp>
#include <glm/vec4.hpp>
#include <array>
#include <vector>
